package creditcard.ui;

/*
		A basic implementation of the JDialog class.
*/

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import creditcard.account.factory.GoldCCAccountFactory;
import creditcard.account.factory.PlatinumCCAccountFactory;
import creditcard.account.factory.SilverCCAccountFactory;
import framework.account.factory.IAccountFactory;
import framework.customer.Customer;
import framework.customer.ICustomer;
import framework.ui.AAddAccDialog;

public class JDialog_AddCCAccount extends AAddAccDialog {
   
	public JDialog_AddCCAccount()
	{
		super();
		
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("Add credit card account");
		setModal(true);
		getContentPane().setLayout(null);
		setSize(301,373);
		setVisible(false);
		
		JRadioButton_Gold.setText("Gold");
		JRadioButton_Gold.setActionCommand("Checkings");
		getContentPane().add(JRadioButton_Gold);
		JRadioButton_Gold.setBounds(36,12,84,24);
		
		JRadioButton_Silver.setText("Silver");
		JRadioButton_Silver.setActionCommand("Savings");
		getContentPane().add(JRadioButton_Silver);
		JRadioButton_Silver.setBounds(36,36,84,24);
		
		JRadioButton_Bronze.setText("Bronze");
		JRadioButton_Bronze.setActionCommand("Savings");
		getContentPane().add(JRadioButton_Bronze);
		JRadioButton_Bronze.setBounds(36,60,84,24);
		
		JLabelName.setText("Name");
		getContentPane().add(JLabelName);
		JLabelName.setForeground(java.awt.Color.black);
		JLabelName.setBounds(12,108,48,24);
		
		JLabelStreet.setText("Street");
		getContentPane().add(JLabelStreet);
		JLabelStreet.setForeground(java.awt.Color.black);
		JLabelStreet.setBounds(12,132,48,24);
		
		JLabelCity.setText("City");
		getContentPane().add(JLabelCity);
		JLabelCity.setForeground(java.awt.Color.black);
		JLabelCity.setBounds(12,156,48,24);
		
		JLabelState.setText("State");
		getContentPane().add(JLabelState);
		JLabelState.setForeground(java.awt.Color.black);
		JLabelState.setBounds(12,180,48,24);
		
		JLabelZip.setText("Zip");
		getContentPane().add(JLabelZip);
		JLabelZip.setForeground(java.awt.Color.black);
		JLabelZip.setBounds(12,204,48,24);
		
		getContentPane().add(JTextField_ACNR);
		JTextField_ACNR.setForeground(java.awt.Color.black);
		JTextField_ACNR.setBounds(12,252,96,24);
		
		JLabelExpDate.setText("Exp. Date");
		getContentPane().add(JLabelExpDate);
		JLabelExpDate.setForeground(java.awt.Color.black);
		JLabelExpDate.setBounds(12,276,72,24);
		
		getContentPane().add(JTextField_NAME);
		JTextField_NAME.setBounds(84,108,156,20);
		getContentPane().add(JTextField_CT);
		JTextField_CT.setBounds(84,156,156,20);
		getContentPane().add(JTextField_ST);
		JTextField_ST.setBounds(84,180,156,20);
		getContentPane().add(JTextField_STR);
		JTextField_STR.setBounds(84,132,156,20);
		getContentPane().add(JTextField_ZIP);
		JTextField_ZIP.setBounds(84,204,156,20);
		getContentPane().add(JTextField_ACNR);
		JTextField_ACNR.setBounds(84,252,156,20);
		getContentPane().add(JTextField_ExpDate);
		JTextField_ExpDate.setBounds(84,276,156,20);
		
		JButton_OK.setText("OK");
		JButton_OK.setActionCommand("OK");
		getContentPane().add(JButton_OK);
		JButton_OK.setBounds(48,312,84,24);
		
		JButton_Cancel.setText("Cancel");
		JButton_Cancel.setActionCommand("Cancel");
		getContentPane().add(JButton_Cancel);
		JButton_Cancel.setBounds(156,312,84,24);
		
		JLabelEmail.setText("Email");
		getContentPane().add(JLabelEmail);
		JLabelEmail.setForeground(java.awt.Color.black);
		JLabelEmail.setBounds(12,228,48,24);
		getContentPane().add(JTextField_Email);
		JTextField_Email.setBounds(84,228,156,20);
		//}}
	
		//{{REGISTER_LISTENERS
		SymMouse aSymMouse = new SymMouse();
		JRadioButton_Gold.addMouseListener(aSymMouse);
		JRadioButton_Silver.addMouseListener(aSymMouse);
		JRadioButton_Bronze.addMouseListener(aSymMouse);
		//}}
	}


	//{{DECLARE_CONTROLS
	javax.swing.JRadioButton JRadioButton_Gold = new javax.swing.JRadioButton();
	javax.swing.JRadioButton JRadioButton_Silver = new javax.swing.JRadioButton();
	javax.swing.JRadioButton JRadioButton_Bronze = new javax.swing.JRadioButton();
	
	javax.swing.JLabel JLabelExpDate = new javax.swing.JLabel();
	javax.swing.JTextField JTextField_ExpDate = new javax.swing.JTextField();
	
	javax.swing.JLabel JLabelEmail = new javax.swing.JLabel();
	javax.swing.JTextField JTextField_Email = new javax.swing.JTextField();
	//}}


	class SymMouse extends java.awt.event.MouseAdapter
	{
		public void mouseClicked(java.awt.event.MouseEvent event)
		{
			Object object = event.getSource();
			if (object == JRadioButton_Gold)
				JRadioButtonChk_mouseClicked(event);
			else if (object == JRadioButton_Silver)
				JRadioButtonSav_mouseClicked(event);
			else if (object == JRadioButton_Bronze)
				JRadioButtonBronze_mouseClicked(event);
			
			
		}
	}

	void JRadioButtonChk_mouseClicked(java.awt.event.MouseEvent event)
	{
		JRadioButton_Gold.setSelected(true);
		JRadioButton_Silver.setSelected(false);
		JRadioButton_Bronze.setSelected(false);
	}

	void JRadioButtonSav_mouseClicked(java.awt.event.MouseEvent event)
	{
		JRadioButton_Gold.setSelected(false);
		JRadioButton_Silver.setSelected(true);
		JRadioButton_Bronze.setSelected(false);
	 
	}
	void JRadioButtonBronze_mouseClicked(java.awt.event.MouseEvent event)
	{
		JRadioButton_Gold.setSelected(false);
		JRadioButton_Silver.setSelected(false);
		JRadioButton_Bronze.setSelected(true);
			 
	}

	@Override
	protected ICustomer createCustomer() {
		String clientName=JTextField_NAME.getText();
		String street=JTextField_STR.getText();
		String city=JTextField_CT.getText();
		String zip=JTextField_ZIP.getText();
		String state=JTextField_ST.getText();
		
		try {	
			Date expDate = new SimpleDateFormat("MM/dd/yyyy").parse(JTextField_ExpDate.getText());
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return new Customer(
				clientName,
				street,
				city,
				state,
				zip, null);
	}

	@Override
	protected IAccountFactory selectFactory() {
		if (JRadioButton_Gold.isSelected())
			return new GoldCCAccountFactory();
		else if (JRadioButton_Silver.isSelected())
			return new SilverCCAccountFactory();
		else
			return new PlatinumCCAccountFactory();
	}
}