package banking.ui;

import banking.account.factory.CheckingAccountFactory;
import banking.account.factory.SavingAccountFactory;
import banking.customer.Organization;
import framework.account.factory.IAccountFactory;
import framework.customer.ICustomer;
import framework.ui.AAddAccDialog;


public class JDialog_AddCompAcc extends AAddAccDialog {
    
	public JDialog_AddCompAcc() {
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("Add compamy account");
		setModal(true);
		getContentPane().setLayout(null);
		setSize(298,339);
		setVisible(false);
		
		JRadioButton_Chk.setText("Checkings");
		JRadioButton_Chk.setActionCommand("Checkings");
		getContentPane().add(JRadioButton_Chk);
		JRadioButton_Chk.setBounds(36,12,84,24);
		
		JRadioButton_Sav.setText("Savings");
		JRadioButton_Sav.setActionCommand("Savings");
		getContentPane().add(JRadioButton_Sav);
		JRadioButton_Sav.setBounds(36,36,84,24);
		
		JLabelName.setText("Name");
		getContentPane().add(JLabelName);
		JLabelName.setForeground(java.awt.Color.black);
		JLabelName.setBounds(12,96,48,24);
		
		JLabelStreet.setText("Street");
		getContentPane().add(JLabelStreet);
		JLabelStreet.setForeground(java.awt.Color.black);
		JLabelStreet.setBounds(12,120,48,24);
		
		JLabelCity.setText("City");
		getContentPane().add(JLabelCity);
		JLabelCity.setForeground(java.awt.Color.black);
		JLabelCity.setBounds(12,144,48,24);
		
		JLabelState.setText("State");
		getContentPane().add(JLabelState);
		JLabelState.setForeground(java.awt.Color.black);
		JLabelState.setBounds(12,168,48,24);
		
		JLabelZip.setText("Zip");
		getContentPane().add(JLabelZip);
		JLabelZip.setForeground(java.awt.Color.black);
		JLabelZip.setBounds(12,192,48,24);
		
		JLabelNEmp.setText("No of employees");
		getContentPane().add(JLabelNEmp);
		JLabelNEmp.setForeground(java.awt.Color.black);
		JLabelNEmp.setBounds(12,216,96,24);
		
		JLabelEmail.setText("Email");
		getContentPane().add(JLabelEmail);
		JLabelEmail.setForeground(java.awt.Color.black);
		JLabelEmail.setBounds(12,240,48,24);
		
		getContentPane().add(JTextField_NAME);
		JTextField_NAME.setBounds(120,96,156,20);
		getContentPane().add(JTextField_CT);
		JTextField_CT.setBounds(120,144,156,20);
		getContentPane().add(JTextField_ST);
		JTextField_ST.setBounds(120,168,156,20);
		getContentPane().add(JTextField_STR);
		JTextField_STR.setBounds(120,120,156,20);
		getContentPane().add(JTextField_ZIP);
		JTextField_ZIP.setBounds(120,192,156,20);
		getContentPane().add(JTextField_NoOfEmp);
		JTextField_NoOfEmp.setBounds(120,216,156,20);
		getContentPane().add(JTextField_EM);
		JTextField_EM.setBounds(120,240,156,20);
		
		JButton_OK.setText("OK");
		JButton_OK.setActionCommand("OK");
		getContentPane().add(JButton_OK);
		JButton_OK.setBounds(48,276,84,24);
		
		JButton_Cancel.setText("Cancel");
		JButton_Cancel.setActionCommand("Cancel");
		getContentPane().add(JButton_Cancel);
		JButton_Cancel.setBounds(156,276,84,24);
		
		getContentPane().add(JTextField_ACNR);
		JTextField_ACNR.setBounds(120,72,156,20);
		JLabelAcnr.setText("Acc Nr");
		getContentPane().add(JLabelAcnr);
		
		JLabelAcnr.setForeground(java.awt.Color.black);
		JLabelAcnr.setBounds(12,72,48,24);
		
		//}}
	}

	//{{DECLARE_CONTROLS
	javax.swing.JRadioButton JRadioButton_Chk = new javax.swing.JRadioButton();
	javax.swing.JRadioButton JRadioButton_Sav = new javax.swing.JRadioButton();
	
	javax.swing.JLabel JLabelNEmp = new javax.swing.JLabel();
	javax.swing.JLabel JLabelEmail = new javax.swing.JLabel();
	
	javax.swing.JTextField JTextField_NoOfEmp = new javax.swing.JTextField();
	javax.swing.JTextField JTextField_EM = new javax.swing.JTextField();
	//}}

	@Override
	protected ICustomer createCustomer() {
		String clientName = JTextField_NAME.getText();
		String street = JTextField_STR.getText();
		String city = JTextField_CT.getText();
		String zip = JTextField_ZIP.getText();
		String state = JTextField_ST.getText();
		
		return new Organization(
				clientName,
				street,
				city,
				state,
				zip);
	}

	@Override
	protected IAccountFactory selectFactory() {
		if (JRadioButton_Chk.isSelected())
			return new CheckingAccountFactory();
		else
			return new SavingAccountFactory();
	}

}