package framework.ui;

import framework.account.factory.AccountFactory;
import framework.account.factory.IAccountFactory;
import framework.customer.Customer;
import framework.customer.ICustomer;

public class AddAccDialog extends AAddAccDialog {


	public AddAccDialog() {
		super();

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("Add account");
		setModal(true);
		getContentPane().setLayout(null);
		setSize(283,303);
		setVisible(false);

		JLabelName.setText("Name");
		getContentPane().add(JLabelName);
		JLabelName.setForeground(java.awt.Color.black);
		JLabelName.setBounds(12,84,48,24);

		JLabelStreet.setText("Street");
		getContentPane().add(JLabelStreet);
		JLabelStreet.setForeground(java.awt.Color.black);
		JLabelStreet.setBounds(12,108,48,24);

		JLabelCity.setText("City");
		getContentPane().add(JLabelCity);
		JLabelCity.setForeground(java.awt.Color.black);
		JLabelCity.setBounds(12,132,48,24);

		JLabelState.setText("State");
		getContentPane().add(JLabelState);
		JLabelState.setForeground(java.awt.Color.black);
		JLabelState.setBounds(12,156,48,24);

		JLabelZip.setText("Zip");
		getContentPane().add(JLabelZip);
		JLabelZip.setForeground(java.awt.Color.black);
		JLabelZip.setBounds(12,180,48,24);

		getContentPane().add(JTextField_NAME);
		JTextField_NAME.setBounds(84,84,156,20);
		getContentPane().add(JTextField_CT);
		JTextField_CT.setBounds(84,132,156,20);
		getContentPane().add(JTextField_ST);
		JTextField_ST.setBounds(84,156,156,20);
		getContentPane().add(JTextField_STR);
		JTextField_STR.setBounds(84,108,156,20);
		getContentPane().add(JTextField_ZIP);
		JTextField_ZIP.setBounds(84,180,156,20);

		JButton_OK.setText("OK");
		JButton_OK.setActionCommand("OK");
		getContentPane().add(JButton_OK);
		JButton_OK.setBounds(48,264,84,24);

		JButton_Cancel.setText("Cancel");
		JButton_Cancel.setActionCommand("Cancel");
		getContentPane().add(JButton_Cancel);
		JButton_Cancel.setBounds(156,264,84,24);

		getContentPane().add(JTextField_ACNR);
		JTextField_ACNR.setBounds(84,60,156,20);
		JLabelAcnr.setText("Acc Nr");
		getContentPane().add(JLabelAcnr);

		JLabelAcnr.setForeground(java.awt.Color.black);
		JLabelAcnr.setBounds(12,60,48,24);
		//}}
	}
	
	protected ICustomer createCustomer() {
		String clientName = JTextField_NAME.getText();
		String street = JTextField_STR.getText();
		String city = JTextField_CT.getText();
		String zip = JTextField_ZIP.getText();
		String state = JTextField_ST.getText();
		
		return new Customer(
				clientName,
				street,
				city,
				state,
				zip, null);
	}
	
	protected IAccountFactory selectFactory() {
		return new AccountFactory();
	}

}
